goblintrinketcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('trinkets/', views.trinkets_index, name='index'),
    path('trinkets/<int:trinket_id>/', views.trinkets_detail, name='detail'),
    path('trinkets/create/', views.TrinketCreate.as_view(), name='trinkets_create'),
    path('trinkets/<int:pk>/update/', views.TrinketUpdate.as_view(), name='trinkets_update'),
    path('trinkets/<int:pk>/delete/', views.TrinketDelete.as_view(), name='trinkets_delete'),
    path('trinkets/<int:trinket_id>/add_uses/', views.add_uses, name='add_uses'),
    path('trinkets/<int:trinket_id>/assoc_merchant/<int:merchant_id>/', views.assoc_merchant, name='assoc_merchant'),
    path('trinkets/<int:trinket_id>/unassoc_merchant/<int:merchant_id>/', views.unassoc_merchant, name='unassoc_merchant'),
    path('merchants/', views.MerchantList.as_view(), name='merchants_index'),
    path('merchants/<int:pk>/', views.MerchantDetail.as_view(), name='merchants_detail'),
    path('merchants/create/', views.MerchantCreate.as_view(), name='merchants_create'),
]

main_app/models.py
from django.db import models
from django.urls import reverse

QUESTS = (
    ('F', 'Fetch'),
    ('E', 'Escort'),
    ('G', 'Gather'),
    ('K', 'Kill'),
    ('D', 'Delivery'),
    ('M', 'Mystery'),
    ('L', 'Lore'),
)

class Merchant(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('merchants_detail', kwargs={'pk': self.id})

class Trinket(models.Model):
    name = models.CharField(max_length=100)
    abilities = models.CharField(max_length=100)
    description = models.TextField(max_length=250)

    merchants = models.ManyToManyField(Merchant)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'trinket_id': self.id})

class Uses(models.Model):
    date = models.DateField('date of usage')
    quest = models.CharField(
        max_length=1,
        choices=QUESTS,
        default=QUESTS[0][0]
    )
    details = models.TextField(max_length=250)

    trinket = models.ForeignKey(Trinket, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_quest_display()} on {self.date}: {self.details}"

    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Uses, Merchant

class UsesForm(ModelForm):
  class Meta:
    model = Uses
    fields = ['date', 'quest', 'details']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Trinket, Merchant
from .forms import UsesForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def trinkets_index(request):
  return render(request, 'trinkets/index.html', {
    'trinkets': trinkets
})

def trinkets_index(request):
  trinkets = Trinket.objects.all()
  return render(request, 'trinkets/index.html', { 'trinkets': trinkets })

def trinkets_detail(request, trinket_id):
  trinket = Trinket.objects.get(id=trinket_id)
  id_list = trinket.merchants.all().values_list('id')
  merchants_trinket_doesnt_have = Merchant.objects.exclude(id__in=id_list)
  uses_form = UsesForm()
  return render(request, 'trinkets/detail.html', {
    'trinket': trinket, 'uses_form': uses_form,
    'merchants': merchants_trinket_doesnt_have
  })

def add_uses(request, trinket_id):
  form = UsesForm(request.POST)
  if form.is_valid():
    new_uses = form.save(commit=False)
    new_uses.trinket_id = trinket_id
    new_uses.save()
  return redirect('detail', trinket_id=trinket_id)

class TrinketCreate(CreateView):
  model = Trinket
  fields = '__all__'

class TrinketUpdate(UpdateView):
  model = Trinket
  fields = '__all__'

class TrinketDelete(DeleteView):
  model = Trinket
  success_url = '/trinkets'

def merchants_index(request):
    merchants = Merchant.objects.all()
    return render(request, 'merchants/index.html', {'merchants': merchants})

def merchants_detail(request, merchant_id):
    merchant = Merchant.objects.get(id=merchant_id)
    return render(request, 'merchants/detail.html', {'merchant': merchant})

class MerchantList(ListView):
  model = Merchant

class MerchantDetail(DetailView):
  model = Merchant

class MerchantCreate(CreateView):
  model = Merchant
  fields = '__all__'

def assoc_merchant(request, trinket_id, merchant_id):
    Trinket.objects.get(id=trinket_id).merchants.add(merchant_id)
    return redirect('detail', trinket_id=trinket_id)

def unassoc_merchant(request, trinket_id, merchant_id):
    Trinket.objects.get(id=trinket_id).merchants.remove(merchant_id)
    return redirect('detail', trinket_id=trinket_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

    <h1>About the Goblin Trinket Collector</h1>
    <hr>
    <p>Gathering Trinkets for Goblins Everywhere.</p>
    <footer>All Rights Reserved, &copy; 2022 Goblin Trinket Collector</footer>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Goblin Trinket Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Goblin Trinket Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'merchants_create' %}">Add a Merchant</a></li>
          <li><a href="{% url 'merchants_index' %}">View All Merchants</a></li>
          <li><a href="{% url 'trinkets_create' %}">Add a Trinket</a></li>
          <li><a href="{% url 'index' %}">View All Trinkets</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Goblin Trinket Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

    <h1>Home</h1>

{% endblock %}

main_app/templates/main_app/merchant_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Merchant Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ merchant.name }}</span>
        <p>Location: {{ merchant.location }}</p>
        <p>Description: {{ merchant.description }}</p>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/merchant_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Merchant</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/merchant_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Merchant List</h1>

{% for merchant in merchant_list %}
  <a href="{% url 'merchants_detail' merchant.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ merchant.name }}</span>
            <p>Location: {{ merchant.location }}</p>
            <p>Description: {{ merchant.description }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/trinket_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Trinket</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' trinket.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/trinket_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Trinket</h1>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/trinkets/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Trinket Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ trinket.name }}</span>
        <p>Abilities: {{ trinket.abilities }}</p>
        <p>Description: {{ trinket.description|linebreaks }}</p>
      </div>
    <div class="card-action">
      <a href="{% url 'trinkets_update' trinket.id %}">Edit</a>
      <a href="{% url 'trinkets_delete' trinket.id %}">Delete</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_uses' trinket.id %}" method="POST">
    {% csrf_token %}
    {{ uses_form.as_p }}
    <input type="submit" class="btn" value="Add A Quest Usage">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Quest</th><th>Details</th></tr>
    </thead>
    <tbody>
      {% for uses in trinket.uses_set.all %}
        <tr>
          <td>{{uses.date}}</td>
          <td>{{uses.get_quest_display}}</td>
          <td>{{uses.details}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ trinket.name }}'s Merchants</h3>
    {% if trinket.merchants.count %}
      {% for merchant in trinket.merchants.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              {{ merchant.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'disassoc_merchant' trinket.id merchant.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form> 
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Vendors</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Merchants</h3>
    {% if merchants.count %}
      {% for merchant in merchants.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
             {{ merchant.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_merchant' trinket.id merchant.id %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{trinket.name}} Already Has All Merchants Available</h5>
    {% endif %}
  </div>
</div>
  

<script>
 const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  const selectEl = document.getElementById('id_quest');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/trinkets/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Trinket List</h1>

{% for trinket in trinkets %}
  <div class="card">
    <a href="{% url 'detail' trinket.id %}">
      <div class="card-content">
        <span class="card-title">{{ trinket.name }}</span>
        <p>Abilities: {{ trinket.abilities }}</p>
        <p>Description: {{ trinket.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}

{% endblock %}